config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
    root to: "lists#index"

    resources :lists do
      resources :bookmarks, only: [:new, :create] 
    end
    resources :bookmarks, only: [:destroy], as: :delete_bookmark




  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id, message: "already exists in this list"}
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end 

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy 
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end
end

private 

def set_bookmark
  @bookmark = Bookmark.find(params[:id])
end 

def bookmark_params
  params.require(:bookmark).permit(:comment, :list_id, :movie_id)
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @list = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end
  
  def set_list
    @list = list.find(params[:id])
  end


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@movie, @list, @bookmark], url: "/lists/:list_id/bookmarks" do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<% @list.each do |list|%>
    <%= list.name %>
    <p>
      <%= link_to "Show this List", list %>
    </p>
<% end %>

<%= link_to "Create new list", new_list_path  %>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<%= @list.name %>
<h1><%= @list.name %></h1>

<h5>Films dans cette liste :</h2>

<ul>
  <% @list.movies.each do |movie| %>
  <%= render movie %>
  <% all_bookmarks = Bookmark.where(list_id: @list.id) %>
  <% bookmark = all_bookmarks.find{|bookmark| bookmark.movie_id == movie.id} %>
  <%= bookmark.id %>
  <%= link_to "Delete", delete_bookmark_path(bookmark.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %> 
  <% end %> 
</ul>

<%= link_to "Return to all lists", root_path  %>
<%= link_to "Add a bookmark", new_list_bookmark_path(params[:id])  %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Overview</strong>
    <%= movie.overview %>
  </p>

  <p>
    <strong>rating:</strong>
    <%= movie.rating %>
  </p>

  <p>
    <%= image_tag(movie.poster_url, alt: "Affiche du film") %>
  </p>

</div>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
<%= render movie %>
<% end %>